# Generated by Django 5.0.6 on 2024-06-08 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.IntegerField(unique=True, verbose_name='DNI')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='email',
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Disciplina o actividad')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('turno', models.CharField(choices=[('Elegir', 'Elegir'), ('mañana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], max_length=10, verbose_name='Turno')),
                ('entrenador_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.entrenador')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.alumno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.disciplina')),
            ],
        ),
        migrations.AddField(
            model_name='disciplina',
            name='alumno_id',
            field=models.ManyToManyField(through='web.Inscripcion', to='web.alumno'),
        ),
    ]